### ISSUE TITLE
Cleanup of lm and related utils

### ISSUE THREAD

**Issue by ricfog** [shamindras/maars#24]
- [x] Include `.gitattributes` file
- [x] We need to `set.seed` in all our vignette chunks. This is for reproducibility, but to also avoid merge conflicts every time we rebuild the package using `make build_package`
- [x] **roxygen2:** Rewrite documentation of the functions making the style more consistent across functions. For example, we could adopt the style used for the [quantile function](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/quantile)
- [x] **roxygen2:** insert dots at end of sentences in Roxygen. [See below](https://github.com/shamindras/maar/issues/24?fbclid=IwAR0JsSrXZGUpYyuizsTFIL8Q0dUvOy_WVbUWBuvZlygg4rmjuo0rU5xNGvM#issuecomment-751913442)
- [x] **roxygen2:** use `@details` responsibly. [See below](https://github.com/shamindras/maar/issues/24?fbclid=IwAR0JsSrXZGUpYyuizsTFIL8Q0dUvOy_WVbUWBuvZlygg4rmjuo0rU5xNGvM#issuecomment-751913442)
- [x] **roxygen2:** replace `var_name` with `\code{var_name}`. [See below](https://github.com/shamindras/maar/issues/24?fbclid=IwAR0JsSrXZGUpYyuizsTFIL8Q0dUvOy_WVbUWBuvZlygg4rmjuo0rU5xNGvM#issuecomment-751913442)
- [x] **ggplot2:** Replace hardcoded values `1.96` with appropriate outputs from statistics functions, in `vignettes`
- [x] Check the order in which we have our functions written in each file
- [x] **ggplot2:** We should break up our `ggplot2` code into separate plots and then combine them using `+`. This will make it much easier to manage the code and make it readable
- [x] **ggplot2:** Need to be consistent with our `ggplot2` themes used in our plots. [See ggplot2 theme wrapper below](https://github.com/shamindras/maar/issues/24?fbclid=IwAR0JsSrXZGUpYyuizsTFIL8Q0dUvOy_WVbUWBuvZlygg4rmjuo0rU5xNGvM#issuecomment-751917061)
- [x] **ggplot2:** Need to be consistent with the `ggplot2` font and other settings used in our plots. As a preference we should only use `labs` for example. [See ggplot2 theme wrapper below](https://github.com/shamindras/maar/issues/24?fbclid=IwAR0JsSrXZGUpYyuizsTFIL8Q0dUvOy_WVbUWBuvZlygg4rmjuo0rU5xNGvM#issuecomment-751917061)
- [x] **ggplot2:** Add `names_prefix = "q"` to `pivot_wider` for the `ggplot2` code i.e. to avoid **.data$`0.275`** issue. Note the `"q"` here stands for `quantile`.
- [x] Create a `utils-common.R` similar to the [selectiveInference package](https://github.com/selective-inference/R-software/blob/master/selectiveInference/R/funs.common.R#L87-L123), ensure that common functions are put in this file
- [x] clean up the `tests` directory i.e. delete unused `R` test files
- [x] clean up the `R` directory i.e. delete unused `R` files
- [x] We should add `#' @importFrom rlang .data` in all our functions under `#' @export`

**Comment by shamindras** [comment]
For `roxygen2` documentation, we can adopt the following convention, 
[mainly from Hadley Wickham's R packages section](https://r-pkgs.org/man.html#man-data), 
but with some changes. Some guidelines specific to our package are:

1. The first line is the high level title. It should not end in a period `.` [see here](https://github.com/shamindras/maar/blob/iss-09-bootstrap-impl-02/R/boot-empirical-var.R#L1)
2. There should be a 1 line gap between all main fields e.g. between `@param` and `@return`. This is a little unconventional, but I feel good practice, [see here](https://github.com/shamindras/maar/blob/iss-09-bootstrap-impl-02/R/boot-empirical-var.R#L1-L24).
3. The first line of the description should begin with `code{function_name}`, [see here](https://github.com/shamindras/maar/blob/iss-09-bootstrap-impl-02/R/boot-empirical-var.R#L3).
4. For the `@examples` section we should always use set.seed for reproducibility, [see here](https://github.com/shamindras/maar/blob/iss-09-bootstrap-impl-02/R/boot-empirical-var.R#L27).
5. Any block that begins with a keyword e.g. `@details`, `@param`, `@return` etc, and is split over multiple lines, should have the second and onward lines indented by 2 spaces, [see here](https://github.com/shamindras/maar/blob/iss-09-bootstrap-impl-02/R/boot-empirical-var.R#L27).
6. We should use indented code blocks in our `@examples` section, [see here](https://github.com/shamindras/maar/blob/iss-09-bootstrap-impl-02/R/boot-empirical-var.R#L27)
7. Each specification of @param should start as "A numeric/character/etc scalar/vector/etc; ..." or  "A numeric/character/etc scalar/vector/etc indicating ...."

**Comment by shamindras** [comment]
For the `ggplot2` wrapper, we can do something simple like this and put in our `utils-common.R`:

``` R
#' Set the custom \code{\link[ggplot2]{theme}} for our plots
#' 
#' \code{set_ggplot2_theme} is a wrapper to set a standard custom 
#' \code{\link[ggplot2]{theme}} for all of our output plots. It contains 
#' only the necessary parameters we require to change in the
#' \code{\link[ggplot2]{theme}} function, and takes the remaining arguments
#' as the default values.
#'
#' @param ggplot_obj A \code{\link[ggplot2]{ggplot2}} object
#' @param axis_text_size A positive integer to define the the size of the x and 
#'   y axis text in our \code{\link[ggplot2]{ggplot2}} object
#' @param axis_title_size A positive integer to define the the size of the x and 
#'   y axis text in our \code{\link[ggplot2]{ggplot2}} object 
#' @param strip_text_x_size A positive integer to define the the size of the x and 
#'   y axis text in our \code{\link[ggplot2]{ggplot2}} object 
#' @param legend_text_size A positive integer to define the the size of the x and 
#'   y axis text in our \code{\link[ggplot2]{ggplot2}} object 
#' @param legend_title_size A positive integer to define the the size of the x and 
#'   y axis text in our \code{\link[ggplot2]{ggplot2}} object 
#' @param legend_position A character value the position of legends 
#' ("none", "left", "right", "bottom", "top", or two-element numeric vector)
#'
#' @return
#' @export
#'
#' @examples
set_ggplot2_theme <- function(ggplot_obj,
                              axis_text_size = 17,
                              axis_title_size = 17,
                              strip_text_x_size = 17,
                              legend_text_size = 17,
                              legend_title_size = 17,
                              legend_position = "bottom") {
  out <- ggplot_obj +
    ggplot2::theme_bw() +
    ggplot2::theme(
      axis.text = ggplot2::element_text(size = axis_text_size),
      axis.title = ggplot2::element_text(size = axis_title_size),
      strip.text.x = ggplot2::element_text(size = strip_text_x_size),
      legend.text = ggplot2::element_text(size = legend_text_size),
      legend.title = ggplot2::element_text(size = legend_title_size),
      legend.position = legend_position
    )
  
  return(out)
}
```

We could then call on this function as follows:

``` R
library(ggplot2)
p1 <- ggplot2::ggplot(mtcars, aes(x = wt, y = mpg, size = disp)) +
      ggplot2::geom_point()

# Set the theme for a `ggplot2` object with the default options
out <- p1 %>% maars::set_ggplot2_theme(ggplot_obj = .)
```

**NOTE:** This is now created in `utils-common.R`. There is also a `test-utils-common.R` file.
