### ISSUE TITLE
FT: Miscellaneous

### ISSUE THREAD

**Issue by shamindras** [shamindras/maars#58]
Adding in various items here, that don't quite fit in other topics (for now)

**Basic Code improvements (Medium High priority)**

- [ ] Change `maars:::get_plot()` to be an external function, it is currently an internal function
- [ ] For assumption wording in **Well Specified** and **Residual Bootstrap** sections, we need to change `Errors are assumed to be homoscedastic`, _from_ `Residuals are assumed to be homoscedastic`
- [ ] @ricfog @shamindras - add comment section headers to all of our code e.g. in `maars-lm.R` we can have comments that say `# summary.maars_lm ----`. This section header will allow us to use the `Alt + Shift + O` to do code folding in our functions. Will make our life much easier to navigate within these long files! This should first be done on `maars-lm.R` and then reviewed, and then rolled out to other files later
- [ ] Rename function names to be consistent i.e. use functions from `pkgdown` to get metadata
- [ ] Perhaps we do a `CRAN` check, based on the [RStudio checklist](https://github.com/tidyverse/multidplyr/issues/109)?
- [ ] Rename `R` scripts and corresponding `test` `R` scripts
- [ ] Move code and consolidate `R` scripts i.e. see whether we can reduce the number of `R` scripts we are using e.g. `get_confint.R` could perhaps move to `ols-summary.R`
- [ ] Make documentation standardized across all our user facing functions. Make sure that we meet the [RStudio checklist](https://github.com/tidyverse/multidplyr/issues/109)
- [ ] Ensure that our code works on [win-builder](https://win-builder.r-project.org/). This was recommended by Alex. R to check before we submit on `CRAN`
- [ ] Change [this code](https://github.com/shamindras/maars/blob/iss-52-upgrade-prep-demo/R/ols-summary.R#L282-L290) to directly call [`get_mms_rnm_cols_suff`](https://github.com/shamindras/maars/blob/iss-52-upgrade-prep-demo/R/ols-summary.R#L167-L180)
- [ ] @shamindras : Mark our experimental functions as such using the [lifecycle package](https://lifecycle.r-lib.org/articles/communicate.html)
- [ ] Use Student's t distribution in the computation of the confidence interval for the sandwich [here](https://github.com/shamindras/maars/blob/main/R/ols-sandwich-lm-var.R#L65) similarly to what we do for[ confidence intervals](https://github.com/shamindras/maars/blob/652f1a8d57ec9cc0cea236721c4f72d0ed1d2327/R/ols-confint.R#L95). Consult @Arun-Kuchibhotla on how to proceed with this. I (@ricfog ) suggest using the `coeftest` function in the [`lmtest`](https://cran.r-project.org/web/packages/lmtest/index.html) package for generating the summary tables (i.e., coefficients estimates, standard errors, etc.)

**Basic Code improvements (Medium Low priority)**

- [ ] We need to change all of our `NULL` input defaults to be `NA`. This is much easier to incorporate into cross joins of grids than `NULL` values, which can't be assigned to vectors (but `NA` values can be)
- [ ] Currently for `comp_var` our assertion checking for valid inputs is done within individual variance estimation functions rather than at the start of `comp_var`. This can result in many unnecessary computations before a known error will occur. For example consider the following case:

  <details>
  <summary>Click to expand!</summary>

  ``` R
  n <- 1e3
  X <- stats::rnorm(n, 0, 1)
  y <- 2 + X * 1 + stats::rnorm(n, 0, 10)
  lm_fit <- stats::lm(y ~ X)
  # Add valid empirical bootstrap, but failing subsampling with
  # m = n + 1 i.e. m > n
  comp_var(mod_fit = lm_fit,
           boot_emp = list(B = 1e3, m = n + 1), # this works
           boot_sub = list(B = 1e3, m = n + 1), # this will fail since m > n
           boot_res = NULL,
           boot_mul = NULL)
  ```

  </details>

The above code returns the correct assertion error for `boot_sub` but it runs the large `boot_emp` computation first! This is rather unfortunate. Perhaps we should do global input assertion checking outside of our `boot_` functions rather than inside them, to catch this error globally and avoid this unnecessary computation issue.

- [ ] **Memory Profiling:** Use more [memory saving sampling](https://stackoverflow.com/questions/66215962/does-rsamplebootstraps-store-data-rather-than-just-row-indices/66251087#66251087) like `rsample` does. We should use the `lobstr::obj_size` to do all our memory profiling of our returned `maars_lm` objects. See the comment by Dr. Silge in the linked post about using this functionality. The end result is our `maars_lm` objects should not save all the data or indices for bootstrap (ideally) but the pointers to the `B` replicates of these datasets, ready to be called as needed using lazy evaluation
- [ ] **Warnings:** Perhaps we use `message()` instead of `warning()` given [this post](https://reside-ic.github.io/blog/a-warning-about-warning/)

**Speed up the bootstrap functions**

This is from #41

- [ ] Use the [collapse](https://sebkrantz.github.io/collapse/) package to speed up sampling
- [ ] reuse the QR decomposition from `lm` in the regressions fitted in the residual bootstrap
- [ ] check whether the speed gap between our `comp_boot_emp` function and `covBS` from the `sandwich` package is worth justifying the use of that package. Note that `covBS` does not return the coefficients estimates
- [ ] sample rademacher weights with Rcpp in the multiplier bootstrap
- [ ] sample the indices in empirical and multiplier bootstrap in the same way and try sampling the indices in [a list](https://github.com/shamindras/maars/blob/7464e0aa961fe50089e7d88bf7a2d4171a06d19f/R/ols-boot-multiplier.R#L229)

**Ensure our estimator calculates weights correctly**

This is from #16 

- [ ] See if we can use lm.fit weights correctly when in our `qr` variance sandwich estimator

**Improve model diagnostics**

This is from #34 

- [ ] @ricfog - add more testing for diagnostics
- [ ] @ricfog - add testing. Try the [vdiffr package](https://github.com/r-lib/vdiffr)
- [ ] @ricfog - allow user to feed their own set of weights into the function
- [ ] @ricfog - allow users to decide which objects should be added to the plots

**Outstanding items from our Wharton demo (03/19/2021) (Low priority)**

- [ ] Jeff: Consider using vector input for summary
- [ ] Jeff: Look into stargazer output tables
- [ ] RB: Write down documentation for what columns return
- [ ] RF/AK: Weights for linear regression, and diagnostics can be done after the paper is written

**Comment by shamindras** [comment]
**Outstanding items from our Wharton demo (03/19/2021) (Low priority)**
- [ ] Jeff: Consider using vector input for summary
- [ ] Jeff: Look into stargazer output tables
- [ ] RB: Write down documentation for what columns return
- [ ] RF/AK: Weights for linear regression, and diagnostics can be done after the paper is written

**Comment by shamindras** [comment]
**Outstanding items from our Wharton demo (03/19/2021) (Low priority)**
- [ ] Jeff: Consider using vector input for summary
- [ ] Jeff: Look into stargazer output tables
- [ ] RB: Write down documentation for what columns return
- [ ] RF/AK: Weights for linear regression, and diagnostics can be done after the paper is written
